alpha: !!python/object/new:ruamel.yaml.scalarfloat.ScalarFloat
  args:
  - 1.0
  state:
    _e_sign: null
    _e_width: null
    _exp: null
    _m_lead0: 0
    _m_sign: false
    _prec: 1
    _underscore: null
    _width: 3
beam_size: 10
cross_coverage: true
d_model: 256
dc: 32
dim_feedforward: 1024
dropout: !!python/object/new:ruamel.yaml.scalarfloat.ScalarFloat
  args:
  - 0.3
  state:
    _e_sign: null
    _e_width: null
    _exp: null
    _m_lead0: 1
    _m_sign: false
    _prec: 1
    _underscore: null
    _width: 3
early_stopping: false
growth_rate: 24
learning_rate: !!python/object/new:ruamel.yaml.scalarfloat.ScalarFloat
  args:
  - 0.08
  state:
    _e_sign: null
    _e_width: null
    _exp: null
    _m_lead0: 2
    _m_sign: false
    _prec: 1
    _underscore: null
    _width: 4
max_len: 200
nhead: 8
num_decoder_layers: 3
num_layers: 16
patience: 20
self_coverage: true
temperature: !!python/object/new:ruamel.yaml.scalarfloat.ScalarFloat
  args:
  - 1.0
  state:
    _e_sign: null
    _e_width: null
    _exp: null
    _m_lead0: 0
    _m_sign: false
    _prec: 1
    _underscore: null
    _width: 3
